---
title: "&nbsp;"
---

# Collaborators

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE)
library(RefManageR)
library(tidyr)
library(magrittr)
library(igraph)
bib_file <- ReadBib("../../Biblatex/ReferencesBIBLATEX.bib", check = FALSE)
```

<br>

Lines between names indicate coauthorship on publications. 
The darkness of the lines indicates the number of publications.

<br>

```{r, echo=FALSE, results="asis",comment=FALSE}
# Get articles
#x <- c("Article", "InProceedings", "InCollection", "Book", "Conference")
x <- c("Article", "InProceedings", "InCollection", "Book")
articles <- bib_file[grepl(paste(x, collapse = "|"), bib_file$bibtype)]
my_articles <- articles[grepl("Porretta", articles$author)]
my_articles <- my_articles[!(grepl("inpreparation", my_articles$pubstate))]
#my_articles <- my_articles[!(grepl("2007", my_articles$year))]

# Get authors names and cooccurance
coauth <- data.frame(character(), character(), stringsAsFactors=F)
for(i in seq_along(my_articles)) {
  authors <- my_articles[i]$author
  pub_auth <- vector(mode = "character", length = length(authors))
  if(length(pub_auth)>1){
  for(a in seq_along(pub_auth)) {
    pub_auth[a] <- paste(unlist(authors[a]), collapse = " ")
  # coauth <- c(coauth, auth)
    
  }
  coauth<-rbind(coauth,t(combn(pub_auth, m=2)))
  }
}


# Ensure columns are factors with the same levels
coauth$V1 %<>% factor() 
coauth$V2 %<>% factor()
coauth$V1 <- factor(coauth$V1, levels = unique(c(levels(coauth$V1), levels(coauth$V2))))
coauth$V2 <- factor(coauth$V2, levels = unique(c(levels(coauth$V1), levels(coauth$V2))))

#You can now use table (it's not symmetric so use +)
cooctab <- table(coauth$V1, coauth$V2) + table(coauth$V2, coauth$V1)

library(igraph)

# build a graph from the above matrix
g <- graph.adjacency(cooctab, weighted=T, mode = "undirected")
# remove loops
g <- simplify(g)
# set labels and degrees of vertices
V(g)$label <- V(g)$name
V(g)$degree <- degree(g)

# set seed to make the layout reproducible
#set.seed(470)
set.seed(2)
# layout1 <- layout.fruchterman.reingold(g)
layout1 <- layout.lgl(g)
# layout1 <- layout.star(g)
# layout1 <- layout.random(g)
# layout1 <- layout.graphopt(g)
# layout1 <- layout_nicely(g)
# layout1 <- layout.norm(layout1, ymin=-1.5, ymax=1.5, xmin=-1.5, xmax=1.5)
layout1 <- layout.norm(layout1, ymin=0, ymax=2.75, xmin=0, xmax=3)

V(g)$label.cex <- 0.8
V(g)$label.color <- rgb(0, 0, 0, .8)
V(g)$frame.color <- NA
V(g)$color <- "white"#"dodgerblue1"
E(g)$width <- 2.5#E(g)$weight*0.8
E(g)$color <- rgb(0, 0, 0, E(g)$weight/max(E(g)$weight)/1.5)
V(g)$shape <- "circle"
```

```{r, eval= TRUE, fig.show='hold', fig.width = 7.5, fig.height=4.5, out.width='1000px', out.height='600px', fig.align='center', results='asis', message=FALSE, warning=FALSE}
op <- par(mar = rep(0, 4))
plot(0,type='n',axes=FALSE,ann=FALSE, xlim = c(-.25,3.5), ylim = c(0,3))
plot(g, layout=layout1*1, 
     vertex.size = strheight("I") * 2 * 50,
     vertex.label.font=2,                          # Font: 1 plain, 2 bold, 3, italic, 4 bold italic, 5 symbol
    vertex.label.cex=0.75,                           # Font size (multiplication factor, device-dependent)
    vertex.label.dist=0,                          # Distance between the label and the vertex
    #vertex.size=(strwidth(V(g)$label) + strwidth("oo")) * 70,
    #vertex.size2=strheight("I") * 2 * 90,
     rescale=F, add = T, asp=0)
```


<br><br>