---
title: "&nbsp;"
---

# Presentations

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE)
library(RefManageR)
bib_file <- ReadBib("../../Biblatex/ReferencesBIBLATEX.bib", check = FALSE)
```

<br>

## Conferences

```{r, echo=FALSE, results="asis",comment=FALSE}
# Get presentations
pres <- bib_file[grepl("Conference", bib_file$bibtype)]
my_pres <- pres[grepl("Porretta", pres$author)]
my_pres_conf <- my_pres[!grepl("Invited", my_pres$keywords)]
my_pres_invited <- my_pres[grepl("Invited", my_pres$keywords)]

dates <- unlist(unique(my_pres_conf$year))[order(unlist(unique(my_pres_conf$year)),decreasing = TRUE)]
for (date in dates) {
  print(my_pres_conf[list(year=date)], .opts = list(check.entries = FALSE, style="markdown", bib.style ="authoryear", max.names =10, dashed=FALSE))
  cat("\n")
}
```

<br>

## Invited

```{r, echo=FALSE, results="asis",comment=FALSE}
dates <- unlist(unique(my_pres_invited$year))[order(unlist(unique(my_pres_invited$year)),decreasing = TRUE)]

for (date in dates) {
  print(my_pres_invited[list(year=date)],.opts = list(check.entries = FALSE, style="markdown",bib.style ="authoryear" ,max.names =10,dashed=FALSE))
  cat("\n")
}
```

<br><br>