---
title: "&nbsp;"
---

# Presentations

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE)
library(RefManageR)
bib_file <- ReadBib("../../Biblatex/ReferencesBIBLATEX.bib", check = FALSE)
```

```{r, echo=FALSE, comment=FALSE, message=FALSE}
# Get articles
x <- c("Article", "InProceedings", "InCollection", "Book")
articles <- bib_file[grepl(paste(x, collapse = "|"), bib_file$bibtype)]
my_articles <- articles[grepl("Porretta", articles$author)]
my_articles_ref <- my_articles[!grepl("Non-refereed", my_articles$keywords)]
my_articles_nonref <- my_articles[grepl("Non-refereed", my_articles$keywords)]
my_submitted <- my_articles[grepl("submitted", my_articles$pubstate)]
```

```{r, echo=FALSE, results="asis", comment=FALSE}
# Print submitted
if(length(my_submitted)>0){
  cat("<br> \n\n## Submitted \n \n")
dates <- unlist(unique(my_submitted$key))[order(unlist(unique(my_submitted$key)),decreasing = TRUE)]
#Prints recerences
for (bibkey in dates) {
  print(my_submitted[list(key=bibkey)],.opts = list(no.print.fields=c("pubstate"), check.entries = FALSE, style="markdown",bib.style ="authoryear" ,max.names =10,dashed=FALSE))
  cat("\n")
}
}
```

<br>

## Refereed 

```{r, echo=FALSE, results="asis",comment=FALSE}
# Print refereed
dates <- unlist(unique(my_articles_ref$year))[order(unlist(unique(my_articles_ref$year)),decreasing = TRUE)]
for (date in dates) {
  print(my_articles_ref[list(year=date)],.opts = list(check.entries = FALSE, style="markdown",bib.style ="authoryear" ,max.names =10,dashed=FALSE))
  cat("\n")
}
```

<br>

## Non-refereed
```{r, echo=FALSE, results="asis",comment=FALSE}
# Print Non-refereed
dates <- unlist(unique(my_articles_nonref$year))[order(unlist(unique(my_articles_nonref$year)),decreasing = TRUE)]
for (date in dates) {
  print(my_articles_nonref[list(year=date)],.opts = list(check.entries = FALSE, style="markdown",bib.style ="authoryear" ,max.names =10,dashed=FALSE))
  cat("\n")
}
```

<br>

## R Package

```{r, echo=FALSE, results="asis",comment=FALSE}
# Get packages
man <- bib_file[grepl("Misc", bib_file$bibtype)]
my_man <- man[grepl("Porretta", man$author)]



dates <- unlist(unique(my_man$year))[order(unlist(unique(my_man$year)),decreasing = TRUE)]
#Prints recerences
for (date in dates) {
  print(my_man[list(year=date)],.opts = list(check.entries = FALSE, style="markdown",bib.style ="authoryear" ,max.names =10,dashed=FALSE))
  cat("\n")
}
```


<br><br>